DecadeWeb/Controllers/Pages/OrderController.cs
using System.IO;
using System.Web.Mvc;
using DecadeWeb.Controllers.Pages;
using Mset.Exco;
using Mset.Exco.Decade;
using Mset.Extensions;



namespace DecadeWeb.Controllers
{
    [DecadeAuthorize( DecadeRole = DecadeRole.ViewOrders )]
    public class OrderController : BasePageController
    {
        //
        // GET: /Order/
        [ImportModelStateFromTempData]
        public ActionResult Index()
        {
            return RedirectToAction(
                "Index",
                "Tracking" );
        }


        [ExportModelStateToTempData]
        public ActionResult DisplayOrder( int ordernumber )
        {
            if (Helpers.IsPOST)
                return Redirect( Url.DisplayOrder( ordernumber ) );

            d_order order = d_order.GetOrderByOrderNumber(
                DB,
                ordernumber );

            if (order == null)
            {
                ModelState.AddModelError(
                    "DISPLAY_ORDER_NOT_FOUND",
                    $"Order {ordernumber} not found.");
                return RedirectToAction(
                    "Index",
                    "Tracking" );
            }

            order.LoadOrderItems( DB );
            order.LoadShipVendor( DB );
            return View(
                "_OrderDisplay",
                order );
        }


        public ActionResult DisplayInvoice( int invoicenumber )
        {
            if (Helpers.IsPOST)
                return Redirect( Url.DisplayOrderByInvoice( invoicenumber ) );

            d_order order = d_order.GetOrderByInvoiceNumber(
                DB,
                invoicenumber );
            order.LoadOrderItems( DB );
            order.LoadShipVendor( DB );
            return View(
                "_OrderDisplay",
                order );
        }


        public ActionResult YDrive( string allinfo )
        {
            string path = Path.Combine(
                ExcoVars.Variables["FileSys.YDrive"],
                allinfo );
            return File(
                path,
                "image/jpeg" );
        }
    }
}

DecadeWeb/Controllers/Pages/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DecadeWeb.Controllers.Pages;
using Mset.Exco.Decade;
using Mset.Exco.Decade.Extensions;
using Mset.Exco.Extensions;
using DecadeWeb.Models;
using MoreLinq;
using Mset.Extensions;
using LambdaSqlBuilder;
using Dapper;

namespace DecadeWeb.Controllers
{
    [DecadeAuthorize(DecadeRole = DecadeRole.ReportsShop)]
    public class OrdersController : BasePageController
    {
        //
        // GET: /Orders/

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Reports");
        }

        #region List Jobs
        public ActionResult Idle()
        {
            return ListJobs(new OrdersListModel("Idle Orders Since {Date}".FormatWithName(new { Date = DateTime.Now.AddDays(-1.5) }), d_order.GetIdleOrders(DB)));
        }

        public ActionResult OnHold()
        {
            return ListJobs(new OrdersListModel("On Hold Orders", d_order.GetOnHoldOrders(DB)));
        }

        public ActionResult Stock()
        {
            return ListJobs(new OrdersListModel("Stock Orders", d_order.GetStockOrders(DB)));
        }

        public ActionResult NCR()
        {
            return ListJobs(new OrdersListModel("NCR Orders", d_order.GetNCROrders(DB)));
        }
        
        public ActionResult FastTrack()
        {
            return ListJobs(new OrdersListModel("Fast Track Orders", d_order.GetFasttrackOrders(DB)));
        }

        public ActionResult Late()
        {
            return ListJobs(new OrdersListModel("Late Orders", d_orderextensions.GetLateOrders(DB, DateTime.Now.ToWorkDay(3)), true));
        }
        
        public ActionResult HotList()
        {
            return View();
        }

        private ActionResult ListJobs(OrdersListModel model)
        {
            foreach (d_order order in model.Orders)
                order.GetDieNumbers(DB);

            return View("_List", model);
        }
        #endregion

        #region Daily Totals
        public ActionResult DailyTotalsForm(DateTime? startdate, DateTime? enddate, string mode, decimal exchangerate = 1)
        {
            if (!startdate.HasValue || String.IsNullOrEmpty(mode))
                return View("_DailyTotalsForm");


            return Redirect(Url.DailyTotals(startdate.Value, mode, exchangerate, enddate));
        }


        public ActionResult DailyTotals(DateTime startdate, DateTime? enddate, string mode, decimal exchangerate)
        {
            DailyTotalsMode tmpMode;

            switch (mode.ToLower())
            {
                case "invoice":
                    tmpMode = DailyTotalsMode.Invoice;
                    break;

                case "shipped":
                    tmpMode = DailyTotalsMode.Shipped;
                    break;

                default:
                    tmpMode = DailyTotalsMode.Order;
                    break;
            }

            var model = new DailyTotalsModel
            {
                StartDate = startdate.ToFirstDayOfMonth(),
                EndDate = (enddate ?? startdate).AddMonths( 1 ),
                Mode = tmpMode,
                ExchangeRate = exchangerate
            };
            // model.EndDate = model.StartDate.AddMonths(1);

            model.Territories = d_territories.GetTerritories(DB);
            model.Orders = d_order.GetDailyTotals(DB, model.Mode, model.StartDate, model.EndDate);
            return View(model);
        }
        #endregion

        #region Invoice Audit
        [ImportModelStateFromTempData]
        public ActionResult InvoiceAuditForm(DateTime? date)
        {
            if (date.HasValue)
                return Redirect(Url.InvoiceAudit(date.Value));

            return View("_InvoiceAuditForm");
        }

        [ExportModelStateToTempData]
        public ActionResult InvoiceAudit(DateTime date)
        {
            IEnumerable<d_order> orders = d_order.GetInvoiceAuditOrders(DB, date);

            if (!orders.Any())
            {
                ModelState.AddModelError("INVOICE_AUDIT_NO_ORDERS", "No orders found with invoice date of {date}.".FormatWithName(new { date = date.ToShortDateString() }));
                return RedirectToAction("InvoiceAuditForm");
            }

            return View(orders);
        }
        #endregion

        #region Order Action
        [ImportModelStateFromTempData]
        public ActionResult OrderActionForm(int? minorder, int? maxorder, string customercode, DateTime? startdate, DateTime? enddate)
        {
            if (minorder.HasValue && maxorder.HasValue)
                return Redirect(Url.OrderAction(minorder.Value, maxorder.Value, customercode));

            if (startdate.HasValue && enddate.HasValue)
                return Redirect(Url.OrderAction(startdate.Value, enddate.Value, customercode));

            var daysIterator = 0;
            d_order firstOrder = null;

            while (firstOrder.IsNull())
            {
                if (daysIterator >= 7)
                    break;

                firstOrder = d_order.GetFirstOrderOnDate(DB, DateTime.Now.Date.ToWorkDay(daysIterator * -1));
                daysIterator++;
            }

            if (firstOrder == null)
            {
                firstOrder = new d_order
                {
                    ordernumber =  0,
                    orderdate = DateTime.Now
                };
            }

            return View("_OrderActionForm", firstOrder);
        }

        /*
        [ExportModelStateToTempData]
        public ActionResult OrderAction(int? minorder, int? maxorder, string customercode, DateTime? startdate, DateTime? enddate)
        {
            IEnumerable<d_order> orders = new List<d_order>();

            if (minorder.HasValue && maxorder.HasValue)
                orders = d_order.GetOrderAction(DB, minorder.Value, maxorder.Value, customercode);
            else if (startdate.HasValue && enddate.HasValue)
                orders = d_order.GetOrderAction(DB, startdate.Value, enddate.Value, customercode);

            if (!orders.Any())
            {
                ModelState.AddModelError("ORDER_ACTION_NO_ORDERS", "No orders found between {minorder} and {maxorder}.".FormatWithName(new { minorder, maxorder }));
                return RedirectToAction("OrderActionForm");
            }

            return View(orders);
        }
        */

        [ExportModelStateToTempData]
        public ActionResult OrderActionByRange(string datefield, int minorder, int maxorder, string customercode)
        {
            return OrderActionHelper("Orders between {minorder} - {maxorder}".FormatWithName(
                new
                {
                    minorder,
                    maxorder
                }),
                d_order.GetOrderAction(DB, datefield, minorder, maxorder, customercode));
        }

        [ExportModelStateToTempData]
        public ActionResult OrderActionByDateRange(string datefield, DateTime startdate, DateTime enddate, string customercode)
        {
            var mode = "Order Date";

            if (datefield.ContainsIgnoreCase("ship"))
                mode = "Ship Date";
            else if (datefield.ContainsIgnoreCase("invoice"))
                mode = "Invoice Date";

            return OrderActionHelper("{datename} between {startdate} - {enddate}".FormatWithName(
                new
                {
                    datename = mode,
                    startdate = startdate.ToShortDateString(),
                    enddate = enddate.ToShortDateString()
                }),
                d_order.GetOrderAction(DB, datefield, startdate, enddate, customercode));
        }

        [ExportModelStateToTempData]
        public ActionResult OrderActionHelper(string title, IEnumerable<d_order> orders)
        {
            if (!orders.Any())
            {
                ModelState.AddModelError("ORDER_ACTION_NONE_FOUND", "No orders found.");
                return RedirectToAction("OrderActionForm");
            }
            return View("OrderAction", new OrderActionModel{ Orders = orders, Title = title });
        }
        #endregion

        #region Open Orders
        public ActionResult OpenOrdersForm(int? minorder, int? maxorder, string customercode, DateTime? startdate, DateTime? enddate)
        {
            if (minorder.HasValue && maxorder.HasValue)
                return Redirect(Url.OpenOrdersByRange(minorder.Value, maxorder.Value, customercode));

            if (startdate.HasValue && enddate.HasValue)
                return Redirect(Url.OpenOrdersByDateRange(startdate.Value, enddate.Value, customercode));

            if (!customercode.IsNullOrEmpty())
                return Redirect(Url.OpenOrdersByCustomer(customercode));

            var daysIterator = 0;
            d_order firstOrder = null;

            while (firstOrder.IsNull())
            {
                if (daysIterator >= 7)
                    break;

                firstOrder = d_order.GetFirstOrderOnDate(DB, DateTime.Now.Date.ToWorkDay(daysIterator * -1));
                daysIterator++;
            }

            if (firstOrder == null)
            {
                firstOrder = new d_order
                {
                    ordernumber = 0,
                    orderdate = DateTime.Now
                };
            }

            return View("_OpenOrdersForm", firstOrder);
        }

        public ActionResult OpenOrdersByRange(int minorder, int maxorder, string customercode)
        {
            return OpenOrdersHelper(d_order.GetOpenOrdersByRange(DB, minorder, maxorder, customercode));
        }

        public ActionResult OpenOrdersByCustomer(string customercode)
        {
            return OpenOrdersHelper(d_order.GetOpenOrdersByCustomer(DB, customercode));
        }

        public ActionResult OpenOrdersByDateRange(DateTime startdate, DateTime enddate, string customercode)
        {

DecadeWeb/Views/Orders/DailyTotals.cshtml
@using DecadeWeb.Code.Extensions
@model DailyTotalsModel
@{
    ViewBag.Title = "Daily Totals";
}

@section AddtoHead{
    <meta http-equiv="refresh" content="300" />
}

@Html.PageRendered()

@Html.PageTitle( "Daily {mode} Totals - {date}".FormatWithName( new
{
    mode = Model.Mode,
    date = Model.StartDate.ToString( "MMMM yyyy" )
} ) )

<p class="text-center">@DateTime.Now</p>

<div class="row-fluid">
    <div class="span10">
        <table class="table table-condensed table-bordered table-striped">
            <thead>
            <tr>
                <th rowspan="2">Date</th>
                <th colspan="@(Model.Territories.Count() + 1)">Sales</th> @* +1 is for the Misc column where sales go if they do not fall into any other category *@
                <th rowspan="2">Gross Sales</th>
                <th colspan="2">Delivery</th>
                <th rowspan="2">GST</th>
                <th rowspan="2">Total Receivable</th>
                <th rowspan="2">Total W/Exch (No Freight)</th>
                <th colspan="3"># Orders</th>
                <th colspan="5">Job Breakdown</th>
                <th rowspan="2">Paid Jobs</th>
            </tr>
            <tr>
                @foreach (d_territories curTer in Model.Territories)
                {
                    <th>@curTer.name</th>
                }
                <th>Misc.</th> @* Territories *@
                <th>USA</th> @* Delivery *@
                <th>CDN</th> @* Delivery *@
                <th>
                    <abbr title="No charge, rework/repair">NCR</abbr>
                </th> @* # Orders *@
                <th>
                    <abbr title="No charge, new die being build.">NCRS</abbr>
                </th> @* # Orders *@
                <th>
                    <abbr title="Total # of jobs (Including NCR/NCRS)">Jobs</abbr>
                </th> @* # Orders *@
                <th>
                    <abbr title="# of solid orders">S</abbr>
                </th> @* Job Breakdown *@
                <th>
                    <abbr title="# of hollow orders">H</abbr>
                </th> @* Job Breakdown *@
                <th>
                    <abbr title="# of bolster only orders">B</abbr>
                </th> @* Job Breakdown *@
                <th>
                    <abbr title="# of ring only orders">R</abbr>
                </th> @* Job Breakdown *@
                <th>
                    <abbr title="# of misc. only orders">M</abbr>
                </th> @* Job Breakdown *@
        </tr>
        </thead>

        <tbody>
        @{
            DateTime curDate = Model.StartDate;

            while (curDate < Model.EndDate)
            {
                List<d_order> dayOrders;

                if (Model.Mode == DailyTotalsMode.Shipped)
                {
                    dayOrders = Model.Orders.Where( d => d.shipdate.Value.Date == curDate.Date ).ToList();
                }
                else if (Model.Mode == DailyTotalsMode.Invoice)
                {
                    dayOrders = Model.Orders.Where( d => d.invoicedate.Value.Date == curDate.Date ).ToList();
                }
                else
                {
                    dayOrders = Model.Orders.Where( d => d.orderdate.Date == curDate.Date ).ToList();
                }

                if (dayOrders.Any())
                {
                    <tr>
                        @{
                            var orderActionMode = "order";

                            if (Model.Mode == DailyTotalsMode.Invoice)
                            {
                                orderActionMode = "invoice";
                            }
                            else if (Model.Mode == DailyTotalsMode.Shipped)
                            {
                                orderActionMode = "shipped";
                            }
                        }
                        <td>
                            <a href="@Url.OrderAction( curDate,
                                         curDate,
                                         datefield: orderActionMode )" target="_blank">
                                @curDate.ToShortDateString()</a>
                        </td> @* Order Date *@

                        @foreach (d_territories curTer in Model.Territories)
                        {
                            <td class="ralign">@dayOrders.Where( x => x.Customer.territory == curTer.code ).Sum( x => x.SubTotal ).ToCurrency()</td>
                        }
                        <td class="ralign">@dayOrders.Where( x => !( Model.Territories.Select( t => t.code ).Contains( x.Customer.territory ) ) ).Sum( x => x.SubTotal ).ToCurrency()</td>

                        <td class="ralign">@dayOrders.Sum( x => x.SubTotal ).ToCurrency()</td> @* Gross Sales *@
                        <td class="ralign">@dayOrders.Where( c => !c.Customer.territory.EqualsIgnoreCase( "CA" ) ).Sum( x => x.freight ).ToCurrency()</td> @* Non-CA Freight *@
                        <td class="ralign">@dayOrders.Where( c => c.Customer.territory.EqualsIgnoreCase( "CA" ) ).Sum( x => x.freight ).ToCurrency()</td> @* CA Freight *@
                        <td class="ralign">
                            @dayOrders.ApplyExchange( x => x.gst,
                                Model.ExchangeRate ).ToCurrency()</td> @* GST *@
                        <td class="ralign">@dayOrders.Sum( x => x.SubTotal + x.freight ).ToCurrency()</td> @* Total Receivable *@
                        <td class="ralign">@dayOrders.ApplyExchange( Model.ExchangeRate ).ToCurrency()</td> @* Total W/ Exch No Freight *@
                        <td class="ralign">@dayOrders.Count( x => x.ncr )</td> @* NCR Count *@
                        <td class="ralign">@dayOrders.Count( x => x.ncrs )</td> @* NCR Scrap Count *@
                        <td class="ralign">@dayOrders.Count()</td> @* Order Count *@
                        <td class="ralign">@dayOrders.Count( x => x.DieType == DieType.Solid )</td> @* Solid Count *@
                        <td class="ralign">@dayOrders.Count( x => x.DieType == DieType.Hollow )</td> @* Hollow Count *@
                        <td class="ralign">@dayOrders.Count( x => x.DieType == DieType.Bolster )</td> @* Bolster Count *@
                        <td class="ralign">@dayOrders.Count( x => x.DieType == DieType.Ring )</td> @* Ring Count *@
                        <td class="ralign">@dayOrders.Count( x => x.DieType == DieType.Misc )</td> @* Misc Count *@
                        <td class="ralign">@dayOrders.Count( x => x.IsPaidJob )</td> @* Paid Work Count *@
                    </tr>
                }

                curDate = curDate.AddDays( 1 );
            }
        }
        </tbody>

        <tr>
            <td colspan="@(20 + Model.Territories.Count())">&nbsp;</td>
        </tr>

        <!-- Summary Line NO EXCHANGE -->
        <tr>
            <td></td>
            @foreach (d_territories curTer in Model.Territories)
            {
                <td class="ralign">@Model.Orders.Where( x => x.Customer.territory == curTer.code ).Sum( x => x.SubTotal ).ToCurrency()</td>
            }
            <td class="ralign">@Model.Orders.Where( x => !Model.Territories.Select( t => t.code ).Contains( x.Customer.territory ) ).Sum( x => x.SubTotal ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Sum( x => x.SubTotal ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Where( c => !c.Customer.territory.EqualsIgnoreCase( "CA" ) ).Sum( x => x.freight ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Where( c => c.Customer.territory.EqualsIgnoreCase( "CA" ) ).Sum( x => x.freight ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.ApplyExchange( x => x.gst,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Sum( x => x.SubTotal + x.freight + x.gst ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.ApplyExchange( Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Count( x => x.ncr )</td>
            <td class="ralign">@Model.Orders.Count( x => x.ncrs )</td>
            <td class="ralign">@Model.Orders.Count()</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Solid )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Hollow )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Bolster )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Ring )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Misc )</td>
            <td class="ralign">@Model.Orders.Count( x => x.IsPaidJob )</td>
        </tr>


        <!-- EXCHANGE OUTPUT LINE -->
        <tr>
            <td>
                <b>EXCHANGE</b>
            </td>
            @foreach (var curTer in Model.Territories)
            {
                <td class="ralign">
                    @Model.Orders.Where( x => x.Customer.territory.EqualsIgnoreCase( curTer.code ) ).GetExchange( x => x.SubTotal,
                        Model.ExchangeRate ).ToCurrency()</td>
            }
            <td class="ralign">
                @Model.Orders.Where( x => !Model.Territories.Select( t => t.code ).Contains( x.Customer.territory ) ).GetExchange( x => x.SubTotal,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.GetExchange( x => x.SubTotal,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.Where( x => !x.Customer.territory.EqualsIgnoreCase( "CA" ) ).GetExchange( x => x.freight,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.Where( x => x.Customer.territory.EqualsIgnoreCase( "CA" ) ).GetExchange( x => x.freight,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.GetExchange( x => x.gst,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.GetExchange( x => x.SubTotal + x.freight + x.gst,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@(0.ToCurrency())</td>
            <th>NCR</th> @* # Orders *@
            <th>NCRS</th> @* # Orders *@
            <th>Jobs</th> @* # Orders *@
            <th>S</th> @* Job Breakdown *@
            <th>H</th> @* Job Breakdown *@
            <th>B</th> @* Job Breakdown *@
            <th>R</th> @* Job Breakdown *@
            <th>M</th> @* Job Breakdown *@
            <th>Paid</th>
        </tr>


        <!-- Summary Line WITH EXCHANGE -->
        <tr>
            <td>
                <b>TOTALS</b>
            </td>
            @foreach (d_territories curTer in Model.Territories)
            {
                <td class="ralign">@Model.Orders.Where( x => x.Customer.territory == curTer.code ).ApplyExchange( Model.ExchangeRate ).ToCurrency()</td>
            }
            <td class="ralign">@Model.Orders.Where( x => !Model.Territories.Select( t => t.code ).Contains( x.Customer.territory ) ).ApplyExchange( Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.ApplyExchange( Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.Where( c => !c.Customer.territory.EqualsIgnoreCase( "CA" ) ).ApplyExchange( x => x.freight,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.Where( c => c.Customer.territory.EqualsIgnoreCase( "CA" ) ).ApplyExchange( x => x.freight,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.ApplyExchange( x => x.gst,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">
                @Model.Orders.ApplyExchange( x => x.SubTotal + x.freight + x.gst,
                    Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.ApplyExchange( Model.ExchangeRate ).ToCurrency()</td>
            <td class="ralign">@Model.Orders.Count( x => x.ncr )</td>
            <td class="ralign">@Model.Orders.Count( x => x.ncrs )</td>
            <td class="ralign">@Model.Orders.Count()</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Solid )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Hollow )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Bolster )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Ring )</td>
            <td class="ralign">@Model.Orders.Count( x => x.DieType == DieType.Misc )</td>
            <td class="ralign">@Model.Orders.Count( x => x.IsPaidJob )</td>
</tr>
</table>
</div>
</div>

DecadeWeb/Views/Orders/ManageHold.cshtml
@{
    ViewBag.Title = "Place orders on/off hold";
}

@Html.PageTitle( ViewBag.Title as string )


<form id="holdform">
    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="ordernumbers">
                Order Number(s):
            </label>
        </div>
        <div class="span6">
            <input type="text" name="ordernumbers" id="ordernumbers" data-bind="value: orders" class="input-large focus"/>
        </div>
    </div>

    <fieldset id="holdtype">

        <div class="row-fluid">
            <div class="offset6 span6">
                <label>
                    <input type="radio" name="holdtype" value="onhold" data-bind="checked: mode"/>
                    On Hold
                </label>
            </div>
        </div>

        <div class="row-fluid">
            <div class="offset6 span6">
                <label>
                    <input type="radio" name="holdtype" value="release" data-bind="checked: mode"/>
                    Release
                </label>
            </div>
        </div>

        <div class="row-fluid">
            <div class="offset6 span6">
                <label>
                    <input type="radio" name="holdtype" value="remove" data-bind="checked: mode"/>
                    Remove
                </label>
            </div>
        </div>

    </fieldset>

    <div class="row-fluid">
        &nbsp;
    </div>

    <div class="row-fluid">
        <div class="span12 text-center">
            <input type="button" class="btn btn-primary" id="processhold" data-bind="enable: CanSubmit()" value="Process"/>
        </div>
    </div>
</form>

@section script
{
    <script type="text/javascript">
        var VM = new ManageHoldViewModel();
    </script>
}

DecadeWeb/Views/Orders/_OrderActionForm.cshtml
@model d_order
@{
    ViewBag.Title = "Order Action";
}

@Html.PageTitle( ViewBag.Title as string )

@using (Html.BeginForm( "OrderActionForm",
    "Orders" ))
{
    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="minorder">
                Start:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small" id="minorder" name="minorder" value="@Model.ordernumber"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="maxorder">
                End:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small" id="maxorder" name="maxorder" value="999999"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="ordercustomercode">
                Customer:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small customerautocomplete" id="ordercustomercode" name="customercode" placeholder="Customer"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12 text-center">
            <button type="submit" class="btn btn-primary">
                View
            </button>
        </div>
    </div>
}

@using (Html.BeginForm( "OrderActionForm",
    "Orders" ))
{
    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="startdate">
                Start Date:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small datepicker" id="startdate" name="startdate" value="@Model.orderdate.ToShortDateString()"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="maxorder">
                End:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small datepicker" id="enddate" name="enddate" value="@Model.orderdate.ToShortDateString()"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="datecustomercode">
                Customer:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small customerautocomplete" id="datecustomercode" name="customercode" placeholder="Customer"/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12 text-center">
            <button type="submit" class="btn btn-primary">
                View
            </button>
        </div>
    </div>
}