DecadeWeb/Controllers/Pages/SteelInventoryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DecadeWeb.Controllers.Pages;
using Mset.Exco.Decade;
using Mset.Extensions;



namespace DecadeWeb.Controllers
{
    [DecadeAuthorize( DecadeRole = DecadeRole.Steel | DecadeRole.SteelPricing )]
    public class SteelInventoryController : BasePageController
    {
        //
        // GET: /SteelInventory/

        // [OutputCache(Duration = Int32.MaxValue, Location = System.Web.UI.OutputCacheLocation.ServerAndClient, VaryByParam = "*", VaryByCustom = "User")]
        [ImportModelStateFromTempData]
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Display( string filter, double? diameter )
        {
            return View(
                inv_steel.GetSteelInventory(
                    DB,
                    filter,
                    diameter ) );
        }


        [DecadeAuthorize( DecadeRole = DecadeRole.SteelPricing )]
        public ActionResult Add( string json )
        {
            if (!json.IsNullOrEmpty())
                return View( "Inserted" );

            IEnumerable<inv_vendors> Vendors = inv_vendors.GetVendors( DB );

            if (!Vendors.Any())
                Vendors = new List<inv_vendors>();

            return View( Vendors );
        }


        public ActionResult Edit()
        {
            return View( inv_steel.GetSteelInventory( DB ) );
        }


        [ImportModelStateFromTempData]
        public ActionResult ViewBarForm( string barid )
        {
            if (!barid.IsNullOrEmpty())
                return Redirect( Url.SteelInventoryViewBar( barid ) );

            return View( "_ViewBarForm" );
        }


        [ExportModelStateToTempData]
        public ActionResult ViewBar( string barid )
        {
            inv_steel bar = inv_steel.GetBarByID(
                DB,
                barid );

            if (bar == null)
            {
                ModelState.AddModelError(
                    "STEEL_INV_NO_BAR",
                    $"Bar {barid} not found." );
                return RedirectToAction( "ViewBarForm" );
            }

            return View( bar );
        }
    }
}

DecadeWeb/Controllers/Services/SteelInventoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web.Http;
using Dapper;
using LambdaSqlBuilder;
using Mset.Exco.Decade;
using Mset.Extensions;
using Newtonsoft.Json;



namespace DecadeWeb.Controllers.Services
{
    public class SteelInventoryController : BaseApiController
    {
        [AcceptVerbs( "POST", "GET" )]
        public dynamic InsertBars( [FromBody] string json )
        {
            using (DbTransaction trans = DB.Connection.BeginTransaction())
            {
                dynamic bars = JsonConvert.DeserializeObject( json );
                var curDate = DateTime.Now;

                foreach (dynamic Bar in bars)
                {
                    if (Bar == null
                        || !String.IsNullOrEmpty( Bar["NumID"].ToString().Trim() ))
                        continue;

                    double diameter = -1;
                    if (String.IsNullOrEmpty( Bar["Diameter"].ToString().Trim() )
                        || !Double.TryParse(
                            Bar["Diameter"].ToString(),
                            out diameter ))
                        continue;
                    // Valid Bar
                    string material = Bar["Material"].ToString();


                    #region Get Bar Group Info
                    var query = new SqlLam<inv_steelinf>()
                        .Where( x => x.Material == material )
                        .Where( x => x.Dia == diameter );

                    var barGroup = DB.Connection.Query<inv_steelinf>(
                        query,
                        trans ).SingleOrDefault();

                    if (barGroup.IsNull())
                    {
                        barGroup = new inv_steelinf
                        {
                            Material = material,
                            Dia = diameter
                        };
                        barGroup.Update(
                            DB,
                            trans,
                            true );

                        // Get the ID of the newly inserted Group
                        barGroup = DB.Connection.Query<inv_steelinf>(
                            query,
                            trans ).SingleOrDefault();
                    }
                    #endregion


                    #region Insert Bar Into Database
                    var strMatCode = barGroup.Material.Equals("HOT VAR")
                        ? barGroup.Material.Substring(0, 2)
                        : barGroup.Material.Substring(0, 1);

                    var bar = new inv_steel
                    {
                        BarInf = barGroup.ID.Value,
                        DateIn = curDate,
                        lastchange = curDate,
                        Length = Convert.ToDouble( Bar["Length"] ),
                        PrevLength = Convert.ToDouble( Bar["Length"] ),
                        TrueDia = Convert.ToDouble( Bar["TrueDia"] ),
                        lbPrice = Convert.ToDouble( Bar["lbPrice"] ),
                        vendorid = Convert.ToInt32( Bar["vendorid"] ),
                        heatnumber = Bar["heatnumber"],
                        NumID = $"{strMatCode}-{barGroup.Dia}-"
                    };


                    #region Get Next BarID (NumID)
                    double tmpDia = Convert.ToDouble( Bar["Diameter"] );
                    var barIDQuery = new SqlLam<inv_steel>()
                        .Top( 1 )
                        .Select( x => x.NumID )
                        .OrderByDescending(
                            x => new
                            {
                                x.DateIn,
                                x.NumID
                            } )
                        .JoinInner<inv_steelinf>( ( inv_steel, inv_steelinf ) => inv_steel.BarInf == inv_steelinf.ID )
                        .Select( x => x.Dia )
                        .Where( x => x.Material == material )
                        .Where( x => x.Dia == tmpDia );

                    var tmpBar = DB.Connection.Query<inv_steel, inv_steelinf, inv_steel>(
                        barIDQuery,
                        ( inv_steel, inv_steelinf ) =>
                        {
                            inv_steel.SteelInformation = inv_steelinf;
                            return inv_steel;
                        },
                        trans,
                        splitOn: "dia" ).SingleOrDefault();

                    if (tmpBar != null)
                    {
                        int barNum = Convert.ToInt32(
                            tmpBar.NumID.Substring(
                                tmpBar.NumID.LastIndexOf(
                                    "-",
                                    StringComparison.Ordinal ) + 1 ) ) + 1;
                        bar.NumID += barNum;
                    }
                    else
                        bar.NumID += "100";
                    #endregion


                    Bar.NumID = bar.NumID;
                    bar.Update(
                        DB,
                        trans,
                        true );
                    #endregion
                }

                trans.Commit();

                return bars;
            }
        }


        [AcceptVerbs( "POST", "GET" )]
        public dynamic CheckBarID( string id )
        {
            inv_steel bar = inv_steel.GetBarByID(
                DB,
                id );

            if (bar != null
                && !bar.DateFin.HasValue)
            {
                return new
                {
                    isValid = true,
                    message = "Valid Bar"
                };
            }

            return new
            {
                isValid = false,
                message = "Invalid Bar ID."
            };
        }


        [AcceptVerbs( "POST", "GET" )]
        public dynamic CheckBarLength( string val, double newLength )
        {
            inv_steel bar = inv_steel.GetBarByID(
                DB,
                val );

            if (bar != null
                && !bar.DateFin.HasValue)
            {
                return newLength < bar.PrevLength
                           ? new
                           {
                               isValid = true,
                               message = "Valid Length"
                           }
                           : new
                           {
                               isValid = false,
                               message = $"Bar should be less than Previous length ({bar.PrevLength})."
                           };
            }

            return new
            {
                isValid = false,
                message = "Invalid Bar ID."
            };
        }


        [AcceptVerbs( "POST", "GET" )]
        public dynamic PostNewBarLengths( [FromBody] string json )
        {
            var errors = new List<string>();
            var changeDate = DateTime.Now;

            using (DbTransaction trans = DB.Connection.BeginTransaction())
            {
                dynamic bars = JsonConvert.DeserializeObject( json );

                foreach (dynamic bar in bars)
                {
                    if (Extension.IsNull( bar )
                        || bar["NumID"] == null
                        || bar["NewLength"] == null)
                        continue;

                    double barLength = -1;
                    if (!String.IsNullOrEmpty( bar["NumID"].ToString().Trim() )
                        && Double.TryParse(
                            bar["NewLength"].ToString(),
                            out barLength ))
                    {
                        DB.Connection.Execute(
                            "UPDATE inv_steel SET PrevLength = @newLength " +
                            ", lastchange = @changeDate " +
                            ( barLength <= 0
                                  ? ", DateFin = @datefin "
                                  : String.Empty ) +
                            "WHERE NumID = @barid",
                            new
                            {
                                barid = bar["NumID"].ToString(),
                                newLength = barLength,
                                datefin = changeDate,
                                changeDate
                            },
                            trans
                            );
                    }
                    else
                    {
                        errors.Add(
                            $"Invald information for Bar {bar["NumID"]}." );
                    }
                }

                trans.Commit();
            }

            return new
            {
                error = errors.Count != 0,
                errors
            };
        }
    }
}

DecadeWeb/Views/SteelInventory/Add.cshtml
@model IEnumerable<inv_vendors>
@{
    ViewBag.Title = "Steel Inventory - Add";
}

@Html.PrintButton()

@Html.PageTitle( ViewBag.Title as string )

@using (Html.BeginForm( "Add",
    "SteelInventory",
    FormMethod.Post,
    new
    {
        id = "addform"
    } ))
{
    <div class="row-fluid">
        <div class="offset1 span10">
            <table class="table" id="newbars">
                <thead>
                <tr>
                    <th>Material</th>
                    <th>Diameter</th>
                    <th>True Diameter</th>
                    <th>Length</th>
                    <th class="noprint">Vendor</th>
                    <th class="noprint">Price/lb.</th>
                    <th>Heat Number</th>
                    <th>Bar ID</th>
                </tr>
                </thead>

                <tbody data-bind="foreach: Bars">
                <tr>
                    <td>
                        <select class="input input-small" name="material" data-bind="value: Material">
                            <option value="H-13">H-13</option>
                            <option value="2714">2714</option>
                            <option value="QRO-90">QRO-90</option>
                            <option value="M2">M2</option>
                            <option value="HOT VAR">HOT VAR</option>
                            <option value="DV">Die Var</option>
                        </select>
                    </td>
                    <td>
                        <div class="control-group" data-bind="validationElement: Diameter, validationOptions: { insertMessages: false }">
                            <input type="text" class="input input-small controls focus" name="diameter" data-bind="value: Diameter"/>
                        </div>
                    </td>
                    <td>
                        <div class="control-group" data-bind="validationElement: TrueDia, validationOptions: { insertMessages: false }">
                            <input type="text" class="input input-small controls" name="truedia" data-bind="    value: TrueDia"/>
                        </div>
                    </td>
                    <td>
                        <div class="control-group" data-bind="validationElement: Length, validationOptions: { insertMessages: false }">
                            <input type="text" class="input input-small controls" name="length" data-bind="    value: Length"/>
                        </div>
                    </td>
                    <td class="noprint">
                        <select class="input input-medium" name="vendor" data-bind="value: vendorid">
                            @foreach (inv_vendors vendor in Model)
                            {
                                <option value="@vendor.VendorID">@vendor.VendorName</option>
                            }
                        </select>
                    </td>
                    <td class="noprint">
                        <div class="control-group" data-bind="validationElement: lbPrice, validationOptions: { insertMessages: false }">
                            <input type="text" class="input input-small controls" name="priceperlb" data-bind="    value: lbPrice"/>
                        </div>
                    </td>
                    <td>
                        <div class="control-group" data-bind="validationElement: heatnumber, validationOptions: { insertMessages: false }">
                            <input type="text" class="input input-small controls" name="heatnumber" data-bind="    value: heatnumber"/>
                        </div>
                    </td>
                    <td>
                        <b id="barid" data-bind="text: NumID"></b>
                    </td>
                </tr>
                </tbody>

                <tfoot>
                <tr class="noprint">
                    <td colspan="8">
                        <p class="text-center">
                            <button type="button" class="btn btn-primary" id="addbars">Enter Into System</button>
                        </p>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
}

@section script
{
    <script type="text/javascript">
        var VM = new SteelInventoryAddBarViewModel();

        $(document).ready(function() {
            $("#newbars").on("keydown", "input", function() {
                AddRow();
            });

            $("#addbars").click(function() {
                $("#addbars").attr('disabled', 'disabled');
                var json = ko.toJSON(VM.Bars());

                $.post("/api/SteelInventory/InsertBars", { "": json }, function() {
                }).done(function(data) {
                    // Update BarID's

                    for (var i = 0; i < data.length; i++) {
                        if (data[i] !== null) {
                            VM.Bars()[i].NumID(data[i].NumID);
                        }
                    }
                    $("#addbars").removeAttr('disabled');
                }).fail(function(jqXHR, textStatus, errorThrown) {
                    $.pnotify({
                        title: "Error",
                        text: "Error while saving.",
                        type: "error"
                    });
                    console.log("Error in Post " + textStatus + " - " + errorThrown + " - " + jqXHR);
                    console.log(jqXHR);
                    $("#addbars").removeAttr('disabled');
                });
            });
        });

        function AddRow() {
            if (!AllRowsFull())
                return;

            VM.AddBar();
        }

        function AllRowsFull() {
            for (var i = 0; i < VM.Bars().length; i++) {
                if (VM.Bars()[i].errors().length > 0) {
                    return false;
                }
            }

            return true;
        }
    </script>
}

DecadeWeb/Views/SteelInventory/Display.cshtml
@model IEnumerable<inv_steel>

@{
    ViewBag.Title = "Steel Inventory";
}

@Html.PrintButton()

@Html.PageRendered()

<h2 class="text-center">@GlobalResources.SteelInv_Title</h2>
<table class="table table-condensed table-striped table-hover table-bordered sortable">
    <thead>
    <tr>
        <th>@GlobalResources.SteelInv_Bar_ID</th>
        <th>@GlobalResources.SteelInv_Material</th>
        <th>@GlobalResources.SteelInv_Diameter</th>
        <th>@GlobalResources.SteelInv_True_Dia</th>
        <th>@GlobalResources.SteelInv_Current_Length</th>
        <th>@GlobalResources.SteelInv_Total_Length</th>
        <th>@GlobalResources.SteelInv_Date_In</th>
        <th>@GlobalResources.SteelInv_Weight</th>
        @if (User.IsInRole( DecadeRole.SteelPricing ))
        {
            <th>@GlobalResources.SteelInv_Price_Per_LB</th>
            <th>@GlobalResources.SteelInv_Bar_Value</th>
        }
        <th>@GlobalResources.SteelInv_Vendor</th>
        <th>@GlobalResources.SteelInv_Heat_Number</th>
    </tr>
    </thead>
    @foreach (var steel in Model)
    {
        <tr>
            <td>
                <a href="@Url.SteelInventoryViewBar( steel.NumID )">@steel.NumID</a>
            </td>
            <td>@steel.SteelInformation.Material</td>
            <td>@steel.SteelInformation.Dia.ToString( "#.###\"" )"</td>
            <td>@steel.TrueDia.ToString( "#.###" )"</td>
            <td>@steel.PrevLength.ToString( "#.###" )"</td>
            <td>@steel.Length.ToString( "#.###" )"</td>
            <td>@steel.DateIn.ToShortDateString()</td>
            <td>@(( steel.TrueDia * steel.TrueDia * steel.PrevLength * .224 ).ToString( "#.##" )) lbs.</td>
            @if (User.IsInRole( DecadeRole.SteelPricing ))
            {
                <td>
                    @(steel.lbPrice.HasValue
                          ? steel.lbPrice.Value.ToString( "C" )
                          : String.Empty)
                </td>
                <td>
                    @(( steel.TrueDia * steel.TrueDia * steel.PrevLength * .224 * ( steel.lbPrice.HasValue
                                                                                        ? steel.lbPrice.Value
                                                                                        : 1.5 ) ).ToString( "C" ))
                </td>
            }
            <td>
                @(steel.VendorInformation != null
                      ? steel.VendorInformation.VendorName
                      : String.Empty)
            </td>
            <td>@steel.heatnumber</td>
        </tr>
    }
</table>

DecadeWeb/Views/SteelInventory/Edit.cshtml
@model IEnumerable<inv_steel>
@{
    ViewBag.Title = "Steel Inventory - Edit";
}

@Html.PageTitle( "Steel Inventory - Edit" )

<div class="row-fluid">
    <div class="offset4 span4">
        <table class="table table-bordered table-condensed table-striped" id="editbars">
            <thead>
            <tr>
                <th>Bar ID</th>
                <th colspan="2">New Length</th>
            </tr>
            </thead>
            <tbody data-bind="foreach: Bars">
            <tr>
                <td>
                    <div class="control-group" data-bind="validationElement: NumID, validationOptions: { insertMessages: false }">
                        <input type="text" class="input-small controls focus" data-bind="value: NumID"/>
                    </div>
                </td>
                <td>
                    <div class="control-group" data-bind="validationElement: NewLength, validationOptions: { insertMessages: false }">
                        <input type="text" class="input-small controls" data-bind="value: NewLength"/>
                    </div>
                </td>
                <td>
                    <p data-bind="validationMessage: NumID"></p>
                    <p data-bind="validationMessage: NewLength"></p>
                </td>
            </tr>
            </tbody>

            <tfoot>
            <tr>
                <td colspan="3">
                    <p class="text-center">
                        <button type="submit" class="btn btn-primary" id="updateinventory">
                            Update
                        </button>
                    </p>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

@section script
{
    <script type="text/javascript">
        var VM = new SteelInventoryEditBarViewModel();

        $(document).ready(function() {
            $("#editbars").on("keydown", "input", function() {
                AddRow();
            });

            $("#updateinventory").click(function() {
                $("#updateinventory").attr('disabled', 'disabled');
                var json = ko.toJSON(VM.Bars());

                $.post("/api/SteelInventory/PostNewBarLengths", { "": json }, function() {
                }).done(function(data) {
                    if (data.error === true) {
                        for (var i = 0; i < data.errors.length; i++) {
                            $.pnotify({
                                title: "Error",
                                text: data.errors[i],
                                type: "error"
                            });
                        }
                    } else {
                        $.pnotify({
                            title: "Success",
                            text: "Information saved successfully",
                            type: "success"
                        });
                    }

                    $("#updateinventory").removeAttr('disabled');
                }).fail(function(jqXHR, textStatus, errorThrown) {
                    $.pnotify({
                        title: "Error",
                        text: "Error while saving.",
                        type: "error"
                    });
                    console.log("Error in Post " + textStatus + " - " + errorThrown + " - " + jqXHR);
                    console.log(jqXHR);

                    $("#updateinventory").removeAttr('disabled');
                });
            });

            // Allow Enter to Move to next Input
            EnterAsATab(jQuery);
        });

        function AddRow() {
            if (!AllRowsFull())
                return;

            VM.AddBar();
        }

        function AllRowsFull() {
            for (var i = 0; i < VM.Bars().length; i++) {
                if (VM.Bars()[i].errors().length > 0) {
                    return false;
                }
            }

            return true;
        }
    </script>
}

DecadeWeb/Views/SteelInventory/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Steel Inventory Options</h2>

<div class="row-fluid">
    @Html.ActionLink( "View Steel Inventory",
        "Display" )
</div>
@if (User.IsInRole( DecadeRole.SteelPricing ))
{
    <div class="row-fluid">
        @Html.ActionLink( "Add Bar Steel",
            "Add" )
    </div>
}
<div class="row-fluid">
    @Html.ActionLink( "Modify Current Bar Stock",
        "Edit" )
</div>
<div class="row-fluid">
    @Html.ActionLink( "View Bar Information",
        "ViewBarForm" )
</div>

DecadeWeb/Views/SteelInventory/Inserted.cshtml
@model IEnumerable<inv_steel>
@{
    ViewBag.Title = "Steel Inventory - Inserted";
}

@Html.PageTitle( ViewBag.Title as string )

DecadeWeb/Views/SteelInventory/ViewBar.cshtml
@model inv_steel
@{
    ViewBag.Title = "View Bar";
}

@Html.PageTitle( ViewBag.Title as string )

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Bar ID</p>
    </div>
    <div class="span6">
        @Model.NumID
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Vendor</p>
    </div>
    <div class="span6">
        @(Model.VendorInformation != null
              ? Model.VendorInformation.VendorName
              : "<Unknown>")
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Heat Number</p>
    </div>
    <div class="span6">
        @Model.heatnumber
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Date In</p>
    </div>
    <div class="span6">
        @Model.DateIn
    </div>
</div>

@if (Model.DateFin.HasValue)
{
    <div class="row-fluid">
        <div class="span6">
            <p class="pull-right">Date Finished</p>
        </div>
        <div class="span6">
            @Model.DateFin.Value
        </div>
    </div>
}

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Initial Length</p>
    </div>
    <div class="span6">
        @Model.Length
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <p class="pull-right">Previous Length</p>
    </div>
    <div class="span6">
        @Model.PrevLength
    </div>
</div>

DecadeWeb/Views/SteelInventory/_ViewBarForm.cshtml
@{
    ViewBag.Title = "View Bar";
}

@Html.PageTitle( ViewBag.Title as string )

@using (Html.BeginForm())
{
    <div class="row-fluid">
        <div class="span6">
            <label class="pull-right" for="barid">
                Bar ID:
            </label>
        </div>
        <div class="span6">
            <input type="text" class="input-small" name="barid" id="barid" placeholder="Bar ID"/>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12 text-center">
            <button type="submit" class="btn btn-primary">View</button>
        </div>
    </div>
}

@section script
{
    @Html.DisplayModelErrors()
}